// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/2273809e3d6c4cb668c8a0b86d854fc04a08e66e/cordova-sqlite-storage/index.d.ts
interface Window {
    sqlitePlugin: SQLitePlugin.SQLite;
}

declare var sqlitePlugin: SQLitePlugin.SQLite;

declare namespace SQLitePlugin {
    type TransactionFunction = (tx: Transaction) => void;

    type SuccessCallback = () => void;
    type DatabaseSuccessCallback = (db: Database) => void;
    type StatementSuccessCallback = (results: Results) => void;
    type TransactionStatementSuccessCallback = (tx: Transaction, results: Results) => void;

    type ErrorCallback = (err: Error) => void;
    type TransactionStatementErrorCallback = (tx: Transaction, err: Error) => boolean | void;

    interface OpenArgs {
        name: string;
        location?: string;
        iosDatabaseLocation?: string;
        androidDatabaseImplementation?: number;
        androidLockWorkaround?: number;
        createFromLocation?: number;
        [key: string]: any;
    }
    interface DeleteArgs {
        name: string;
        location?: string;
        iosDatabaseLocation?: string;
    }

    interface Results {
        rowsAffected: number;
        insertId?: number;
        rows: {
            length: number;
            item(i: number): any;
        };
    }

    interface Transaction {
        executeSql(statement: string, params?: any[], success?: TransactionStatementSuccessCallback, error?: TransactionStatementErrorCallback): void;
    }

    interface Database {
        transaction(fn: TransactionFunction, error?: ErrorCallback, success?: SuccessCallback): void;
        readTransaction(fn: TransactionFunction, error?: ErrorCallback, success?: SuccessCallback): void;

        executeSql(statement: string, params?: any[], success?: StatementSuccessCallback, error?: ErrorCallback): void;
        sqlBatch(sqlStatements: Array<string|[string, any[]]>, success?: SuccessCallback, error?: ErrorCallback): void;

        close(success?: SuccessCallback, error?: ErrorCallback): void;
    }

    interface SQLite {
        openDatabase(args: OpenArgs, success?: DatabaseSuccessCallback, error?: ErrorCallback): Database;
        deleteDatabase(args: DeleteArgs, success?: SuccessCallback, error?: ErrorCallback): void;
        selfTest(success?: SuccessCallback, error?: ErrorCallback): void;
        echoTest(ok?: (value: string) => void, error?: (msg: string) => void): void;
    }
}
